spring:
  application:
    name: Iron Invoice Worker
  rabbitmq:
    host: rabbitmq
    username: dev
    password: dev

  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          json_format_mapper: dev.riddle.ironinvoice.worker.shared.config.Jackson3JsonFormatMapper
